### ISSUE TITLE
Group UUIDs are not preserved

### ISSUE THREAD

**Issue by wellread1** [lukeIam/KeePassSubsetExport#1]
This is an interesting plugin.  However, I notice a couple of issues which I will report separately.

KeePass export preserves Group UUIDs during export.  You can verify this by performing a set of sequential exports and examining the Group UUIDs.

The KeePassSubsetExport plugin generates new Group UUIDs during export.  This is a problem because KeePass uses UUIDs to determine if an object (e.g. a Group) is the same or different.  If an exported database is subsequently imported back into its source database, KeePass will treat the groups that have different UUIDs as different, resulting in the import of orphan groups.

**Comment by lukeIam** [comment]
> The KeePassSubsetExport plugin generates new Group UUIDs during export. This is a problem because KeePass uses UUIDs to determine if an object (e.g. a Group) is the same or different. If an exported database is subsequently imported back into its source database, KeePass will treat the groups that have different UUIDs as different, resulting in the import of orphan groups.

Yes the group ids are different - for strict one way exports (like mine) it doesn't matter.
But I will have a look on it...
Maybe we can also transfer other group properties.

**Comment by lukeIam** [comment]
> If you are interested in trimming the empty exported groups automatically it may be useful to examine the KeePass option that does this, i.e., 'Tools>Database Tools>Delete Empty Groups`

I'm just creating groups that are required: 
- have an entry
- have a required child group

I added some code that will assign all (?) group properties to the target groups:
https://github.com/lukeIam/KeePassSubsetExport/pull/4 Please test if it works as you intended.
