### ISSUE TITLE
Sincronization 

### ISSUE THREAD

**Issue by h3ct0r12** [lukeIam/KeePassSubsetExport#11]
I begin to use plugin and is very useful, 
if plugin also take in care a sincronization to the tagged export file will be perfect. 
1st - export main keepass database to a file the tagged entries 
2nd - some entries are modified in my mobile 
3rd - next main database export sincronize mobile changes to the main keepass file

That will be perfect.

**Comment by lukeIam** [comment]
Hi @h3ct0r12,
thanks for using KeePassSubsetExport.

Im sorry, but KeePassSubsetExport was build as (one-way) exporter.
Maybe I will develop an other plugin for two-way sync in the future, if I'll find the time for it.
