### ISSUE TITLE
required prefix on config entry title

### ISSUE THREAD

**Issue by bmcdonnell** [lukeIam/KeePassSubsetExport#13]
Minor usability issue: It isn't clear from `README.md` that entry *titles* in the `SubsetExportSettings` folder must begin with the `SubsetExport_` prefix in order to be processed. (The example is `SubsetExport_MobilePhone`.)

Please either remove this requirement (preferred, I think), or document it in `README.md`.

**Comment by lukeIam** [comment]
> Please either remove this requirement (preferred, I think)

I agree it's better to remove it...
