### ISSUE TITLE
Plugin size

### ISSUE THREAD

**Issue by genaDeus** [lukeIam/KeePassSubsetExport#15]
Hi man!

4 Mb for a plugin? Not much? It's bigger than keepass executable :)

**Comment by lukeIam** [comment]
Hi @genaDeus,

the compiled `KeePassSubsetExport.dll` is just 17KB (KeePassSubsetExport is a small plugin with about 360 lines of code + 206 bytes for the icon).
Looks like KeePass adds some additional files to the plgx-file to make it version independent.
But that's a KeePass thing and I can't influence it (see https://keepass.info/help/v2_dev/plg_index.html#plgx).

**Comment by lukeIam** [comment]
I've read the keepass documentation again and it seems that smaller pglx files are possible.
I have to do some tests but it looks like the next version will be smaller...

**Comment by lukeIam** [comment]
> I have to do some tests but it looks like the next version will be smaller...

https://github.com/lukeIam/KeePassSubsetExport/releases/tag/3.0.1  
=> 504KB

**Comment by genaDeus** [comment]
@lukeIam, thanks a lot! It's much nicer now :)
