### ISSUE TITLE
feature: selective disable

### ISSUE THREAD

**Issue by bmcdonnell** [lukeIam/KeePassSubsetExport#17]
I'd like to be able to selectively disable a `SubsetExport_` job.

The obvious UI would be to add another (faux bool) string field, but that seems a little tedious to use. I think an option in the entries' right-click context menu would be preferred ([example](https://github.com/luckyrat/KeePass-Favicon-Downloader/blob/4082458e3a5b578ed492225860730be4eed9ad2d/KeePassFaviconDownloaderExt.cs#L91)) - I'm not sure if it's possible to limit that to the `SubsetExport_` entries, though.

Thoughts?

**Comment by bmcdonnell** [comment]
On further reflection, a reasonably user-friendly way to implement this as a user, without having the feature, would be to create another group e.g. `SubsetExportSettings_DISABLED`, and just drag the entries there when I don't want to use them, and drag them back to `SubsetExportSettings` when I do.

What do you think? Is the feature suggested above worthwhile? (If so, which UI?) Or would you just have users do my workaround described here?

**Comment by lukeIam** [comment]
> would be to create another group e.g. SubsetExportSettings_DISABLED, and just drag the entries there when I don't want to use them, and drag them back to SubsetExportSettings when I do.

In my opinion thats the easiest method. The user can clearly see which jobs are active without checking the string fields of each entry.

**Comment by bmcdonnell** [comment]
That works.

Think it's worth a mention in the README? (I'm on the fence, so don't take that as a recommendation.)

**Comment by lukeIam** [comment]
> Think it's worth a mention in the README? (I'm on the fence, so don't take that as a recommendation.)

Won't hurt 😉
