### ISSUE TITLE
Multiple Group export

### ISSUE THREAD

**Issue by aurel0698** [lukeIam/KeePassSubsetExport#19]
Hi,

First, thanks for your plugin, it works perfectly, i just have a little problem : 

I want to export two different groups to a single database (if i make two export entries the last override the first), is there a way to do this ?

Thanks for the answer.

**Comment by lukeIam** [comment]
> I want to export two different groups to a single database (if i make two export entries the last override the first), is there a way to do this ?

Hi @aurel0698,

at the moment unfortunately not...
But I'm thinking of a "use existing db and overwrite existing/older entries" features (but don't have time atm).

**Comment by aurel0698** [comment]
Hi Lukelam,

Thanks for your answer.
