### ISSUE TITLE
Custom Icons are not exported

### ISSUE THREAD

**Issue by wellread1** [lukeIam/KeePassSubsetExport#2]
KeePassSubsetExport does not export custom icons.  The \<CustomIcons> node that contains exported custom icon data is missing from the \<Meta> node.  This causes entries that have custom icons to lose their icon.

**Comment by lukeIam** [comment]
Hi @wellread1,

i do not use custom icons...
But I've added custom icon support: #3 
Can you please test the changes?

**Comment by wellread1** [comment]
The enhanced version of KeePassSubsetExport exports the entry custom icon and correctly display the assigned custom icon.

Custom group icons are not displayed.

**Comment by lukeIam** [comment]
> Custom group icons are not displayed.

I fixed this with #1 and prepared a new version: #5

**Comment by wellread1** [comment]
Version 5 looks good.  When I export from a large database containing a large number of custom icons everything important is preserved and the final database is less the half the size of a comparable export using the trigger export method.  I think that this is largely due to the fact you excluded extraneous data such as unused icons, groups, and the deleted objects.

I could think of some additional features, but the plugin is quite polished as it stands now.

**Comment by lukeIam** [comment]
@wellread1 Thanks for testing!
