### ISSUE TITLE
Support Argon2 settings if set in source database

### ISSUE THREAD

**Issue by PhilZ-cwm6** [lukeIam/KeePassSubsetExport#20]
Hi,

Many thanks for your great tool. However, it should be nice if you can preserve the encryption settings of source base, mainly if Argon2 is set

Best regards

**Comment by lukeIam** [comment]
> However, it should be nice if you can preserve the encryption settings of source base, mainly if Argon2 is set

I agree, Argon2 support would be nice -> it's on my list

**Comment by lukeIam** [comment]
Found some bugs while writing test cases but there're nearly fixed...
