### ISSUE TITLE
Partitial fields export

### ISSUE THREAD

**Issue by genaDeus** [lukeIam/KeePassSubsetExport#24]
Hi, Luke!

Is it possible to export only a part of the password entry? E.g. to export only Login and Password while ignoring all other fields like comments and additional fields? Or history of changes?

Maybe by adding a config fields like "SubsetExport_DenyFields", ""SubsetExport_AllowFields"

**Comment by genaDeus** [comment]
Yes, I have other fields where some secondary but still important info are saved. E.g. phone numbers, addresses, secure questions etc. And I do not want to export it to mobile verison or any other partitial database for understandable reasons.
As to me the key feature of your plugin is to export only the part of the base. So the part of the record is the same :)

**Comment by jdrch** [comment]
@genaDeus 

I can definitely see a use case for it: for example if you wanna share an account's username and password without sharing the account recovery and security info (the latter would pretty much give the sharee permanent access to the account unless it was changed _in addition to_ the password).

One could argue from a security perspective that once you share credentials on a non-2FA account you're basically ceding control of that account anyway, since the person you're sharing with can pretty much instantly change the credentials and lock you out. In other words, if you don't trust the sharee (or their security environment) with your recovery info, you shouldn't trust them with your login credentials, either.

Another option would be to create a separate entry for metadata, e.g. Netflix (contains username and password) and Netflix_Info (contains recovery information, etc.), then tag only Netflix for sharing.

**Comment by genaDeus** [comment]
@jdrch 

And I'm using this another opiton exactly. Duplicating the entry and making a second copy with less info is a good workaround. But there is a problem not to forget to update the fields (to be more precise mostly the password field) of the duplicated entry when they are beeing changed in the head one. And of course it's not very convenient when you have a lot of entries duplicated.

**Comment by lukeIam** [comment]
ok - I'll put it on my list

**Comment by bmcdonnell** [comment]
> I thought about a per entry string item

Is there any KeePassSubsetExport info stored here yet? If not, you'd be
introducing a new UI method.

How about a per-tag or per-group string item in the export settings entry?
Then a user could e.g. export two tags from one entry, where one of the
tags hides fields, and the other doesn't. Maybe also give a way to have the
fields be hidden from all exported entries in a given subset export (so
then it applies per-tag, per-group, or to all exported entries converted by
a given export settings entry).

>

**Comment by EnigmaSolved** [comment]
I wonder if adding support in this plugin for KeePass References (#29) would sufficiently address this thread?

**Comment by Angelelz** [comment]
I'm working on this issue in #33 PR. I implemented a new setting SubsetExport_ExportUserAndPassOnly that when true, only Title, Username, Password and Url fields are exported in the job. If anyone wants to alpha test this, there is a plgx file in the branch.
I think this way is easier to implement and apply than a per-entry (or per-tag/group) setting suggested above.
I would also like to discuss if with this setting we should also export other fields like expiration and modification dates or notes.

**Comment by lukeIam** [comment]
> only Title, Username, Password and Url fields are exported in the job

Is this ok or does somebody has a good use case to for a more granular control of the exported fields?

**Comment by jdrch** [comment]
> 
> 
> > only Title, Username, Password and Url fields are exported in the job
> 
> Is this ok or does somebody has a good use case to for a more granular control of the exported fields?

If the account you're exporting is 2FAed, you'll also need to export the backup codes, which may be in a custom field. 

For my use case, I prefer that the _entire_ entry be exported.

**Comment by Angelelz** [comment]
Then you would not need to set this option. Just let it export the entire entry, which is the default!

**Comment by EnigmaSolved** [comment]
> 
> 
> > only Title, Username, Password and Url fields are exported in the job
> 
> Is this ok or does somebody has a good use case to for a more granular control of the exported fields?

Once we get reference support (which I interpret is coming) I think I'll be able to do anything this thread is talking about (eg, by creating a separate record and use references for the parts I want to export, if I'm wanting to not export all data from the original record). But my guess/hunch is that if you add the partial fields export there will eventually be requests for more granular control, so even if you don't add more granular control now you probably want to write you code such that it's easy to add support for more fields later. And/Or, you can just give some detailed instructions in the ReadMe of how this could all be achieved with references and not do partial fields export at all (though I'm in no way against the addition of partial fields export).

**Comment by aflexus** [comment]
@lukeIam , only username & password export is a great option! One thing I'm missing here is items **icons**. Is it possible to export them as well? 
Thank you for a great plugin!

**Comment by lukeIam** [comment]
> @lukeIam , @Angelelz , only username & password export is a great option! One thing I'm missing here is items **icons**. Is it possible to export them as well?

Already supported (even with custom icons), but currently ignored if settings.ExportUserAndPassOnly is set.
I changed this behavior - please give it a try here: https://github.com/lukeIam/KeePassSubsetExport/pull/53

**Comment by lukeIam** [comment]
partial export (username +pw) and ref support already live in the current version
