### ISSUE TITLE
Inactive switch

### ISSUE THREAD

**Issue by CrysK** [lukeIam/KeePassSubsetExport#27]
Is it possible to create a new settings entry for export jobs which are in standby / which I don’t want to use now, but also don’t want to delete.

**Comment by lukeIam** [comment]
Hi @CrysK 

shouldn't be hard - I have to see when I find time for it.
How about setting the entry to expired for disabling it?

**Comment by CrysK** [comment]
> How about setting the entry to expired for disabling it?

Hi @lukeIam, this sounds also great and easy to handle.
