### ISSUE TITLE
KeePass References Support

### ISSUE THREAD

**Issue by EnigmaSolved** [lukeIam/KeePassSubsetExport#29]
Many thanks, @lukeIam, for this excellent plugin! It's been super-useful to me! :)

One thing that would be really helpful though is having support for correctly exporting KeePass Reference data. For example, I have some username/password data to distribute to a colleague: My preference is to create a new group (to be exported via KeePassSubsetExport) with entries that contain usernames/passwords which are References to their original entries. The reason for this is that it can be helpful for me to be able to rename the entries I'm sharing with my colleague so that they better understand what they are to be used for. Currently, the literal Reference strings are what ends up being used (eg, `{REF:P@I:3628.....`) instead of the actual data the references refer to.

It would similarly be useful to me if the password for a given SubsetExportSettings entry (and thus for that exported KeePass Database) could be a reference to another entry outside of the SubsetExportSettings folder. But like the above, the current behavior is that the literal Reference string is what ends up being used as the exported database password (eg, `{REF:P@I:3628.....`) instead of the actual password the reference refers to.

Thanks in advance for considering this request!
:)

**Comment by Angelelz** [comment]
This a great idea for enhancement, it's easy to see an use case for this. That being said, I've been looking around the code, and doing some testing, and it appears Keepass passes the literal reference with the available APIs. The Only way I see to implement this, is hardcoding some checks in the password and username fields for '{REF:' in the beginning.

**Comment by EnigmaSolved** [comment]
Good to know! Perhaps you or @lukeIam could go that route (ie, "hardcoding some checks in the password and username fields for '{REF:' in the beginning") initially in order to get this implemented, but at the same time reach out to the KeePass developers to see about them adding something to the API to better support this scenario (so that eventually it could be done more directly via the API)? Thanks for the legwork you're doing on this! :)

**Comment by Angelelz** [comment]
I was looking around and found in KeePassHttp they implemented it this way:

> internal string[] GetUserPass(PwEntry entry)
>         {
>             return GetUserPass(new PwEntryDatabase(entry, host.Database));
>         }
> 
>         internal string[] GetUserPass(PwEntryDatabase entryDatabase)
>         {
>             // follow references
>             SprContext ctx = new SprContext(entryDatabase.entry, entryDatabase.database,
>                     SprCompileFlags.All, false, false);
> 
>             return GetUserPass(entryDatabase, ctx);
>         }
> 
>         internal string[] GetUserPass(PwEntryDatabase entryDatabase, SprContext ctx)
>         {
>             // follow references
>             string user = SprEngine.Compile(
>                     entryDatabase.entry.Strings.ReadSafe(PwDefs.UserNameField), ctx);
>             string pass = SprEngine.Compile(
>                     entryDatabase.entry.Strings.ReadSafe(PwDefs.PasswordField), ctx);
>             var f = (MethodInvoker)delegate
>             {
>                 // apparently, SprEngine.Compile might modify the database
>                 host.MainWindow.UpdateUI(false, null, false, null, false, null, false);
>             };
>             if (host.MainWindow.InvokeRequired)
>                 host.MainWindow.Invoke(f);
>             else
>                 f.Invoke();
> 
>             return new string[] { user, pass };
>         }

I mostly understand what they did there but I haven't found a way to point to source DB to construct PwEntryDatabase object. As I am just learning to code, let alone OOP, maybe @lukeIam could check it out.

**Comment by Angelelz** [comment]
Well, in my testings I think I made it. I created another pull request and we just have to wait until changes are approved. But if you want to beta test this changes, check my [branched forked repo](https://github.com/Angelelz/KeePassSubsetExport/tree/ReferenceSupport), there is a file KeePassSubsetExport.plgx

**Comment by EnigmaSolved** [comment]
Have not had a chance to test -- been swamped -- but many thanks @Angelelz for your work on this! :)

**Comment by lukeIam** [comment]
> Well, in my testings I think I made it. I created another pull request (#32) and we just have to wait until changes are approved. But if you want to alpha test this changes, check my [branched forked repo](https://github.com/Angelelz/KeePassSubsetExport/tree/ReferenceSupport), there is a file KeePassSubsetExport.plgx

changes are included in the new release
