### ISSUE TITLE
Allow SubsetExportSettings folder in non-root group

### ISSUE THREAD

**Issue by trdischat** [lukeIam/KeePassSubsetExport#37]
@lukeIam, I love your plugin.  I prefer to keep all systems and settings folders, like "Templates", "AutoOpen", "Recycle Bin", etc, in an Admin folder so that they are not mixed in with my "real" groups. But your plugin seems to require that the "SubsetExportSettings" folder be stored in the root of the database.  Would it be possible to allow this folder to live somewhere else?

**Comment by lukeIam** [comment]
I'm trying to find some time for a new release - I'll try to include this one (doesn't look hard to implement)
