### ISSUE TITLE
Multiple Tags/Groups

### ISSUE THREAD

**Issue by MikeW83** [lukeIam/KeePassSubsetExport#38]
Hello,

I'm currently implementing your plugin in our KeePass, but I have problems to configure multiple Groups for synchronization. I always receive this error:
![image](https://user-images.githubusercontent.com/35097389/72972106-19479b00-3dcb-11ea-85e5-386b4b1dd78e.png)
I'm using this setting:

SubsetExport_Group[string field] | Group(s) for filtering (, to delimit multiple groups - , is not allowed in group names) | Yes, if SubsetExport_Tag is set
-- | -- | --

Bit if I use , to separate the groups it doesn't work anymore. Some groups in our databse have spaces in their group name. But also if I select two groups which have a short name and sparate them with , I get the error above.
What I'm doing wrong?

EDIT: And if I set any tag nothing will be exported. Even if I don't use the group setting.

Thank you very much!

Best regards, Michael

**Comment by lukeIam** [comment]
Hi @MikeW83,

sorry for my late reply - were au able to solve this problem in the meanwhile?

The error messages indicates that a group contained on `SubsetExport_Group`  is not found.
Whitespaces should not be a problem, but I found an other problem:
`SubsetExport_Group`=`"Group A,Group B"` -> working
`SubsetExport_Group`=`"Group A, Group B"` -> not working

I'll fix that...

**Comment by lukeIam** [comment]
https://github.com/lukeIam/KeePassSubsetExport/pull/45 should fix the space problem
