### ISSUE TITLE
System Variables

### ISSUE THREAD

**Issue by Mrothyr** [lukeIam/KeePassSubsetExport#39]
I like the plugin. I work on windows with redirected folders and use your plugin for exporting parts of the database for my mobile. I plan to use system variables for use on more than one computer in a domain enviroment. But your plugin produces strange path from it.

From KeyPass Website (https://keepass.info/help/base/placeholders.html): "System environment variables are supported. The name of the variable must be enclosed in '%' characters. For example %TEMP% is replaced by the user's temporary path."

The original Database is on a external drive:
N:\KeePass\Database.kdbx

So I use the following settings:
SubsetExport_KeyFilePath: %appdata%\KeePass\mobile.key

In KeePass the Field is correct show as: \\example.local\shares\home\Redirects\user\Appdata\KeyPass\mobile.key

But when I save it give a error:
SubsetExport: Keyfile is given but could not be found for: Mobile Export

and the path
N:\KeePass\%appdata%\KeePass\mobile.key

It looks like the envirement variables are not parsed correctly in your plugin - its a bug I think. Can you please check this?

**Comment by Mrothyr** [comment]
After a look in the source (I'm not a programmer) I think the problem is in the experter.cs on line 122 and 395.

Insert 
settings.KeyFilePath = Environment.ExpandEnvironmentVariables(settings.KeyFilePath);
and
settings.TargetFilePath = Environment.ExpandEnvironmentVariables(settings.TargetFilePath);
before the 'if (!string.IsNullOrEmpty' statements it should work.

**Comment by lukeIam** [comment]
@Mrothyr thanks for your idea and work!
I've ended up using the string engine of keepass (which also replaces environment variables)

**Comment by Mrothyr** [comment]
Thx ^^
