### ISSUE TITLE
Export to multiple locations

### ISSUE THREAD

**Issue by Imwithstupid007** [lukeIam/KeePassSubsetExport#47]
Hi Lukelam,

Thank for this great plug-in. I use it a lot.

This is not an issue but a suggestion.

Would it be an idea to modify the parameter SubsetExport_TargetFilePath to accept multiple paths.
My usecase is that i use the plugin to generate multiple filtered copies of a main database which i have to store at different locations (like NAS and cloud). The only way to achieve this now is to make multiple subsetexportsettings, which essentially do the same thing except write to another locations.

TIA,,

Jack

**Comment by lukeIam** [comment]
Hi @Imwithstupid007,

should not be hard to implement - I'll try to find time for the change...

**Comment by Imwithstupid007** [comment]
Wow, great,

Thanks a lot.
