### ISSUE TITLE
KeePassSubsetExport - not exporting tagged entries

### ISSUE THREAD

**Issue by BilRadaker** [lukeIam/KeePassSubsetExport#48]
Hi Lukelam,

I have been trying to get  KeePassSubsetExport  working.   Everything appears (to me) to be correct according to the posted instructions.
When I save the Master database, KeePassSubsetExport DOES create a new database in the path that I have indicated, but it does NOT populate any of the tagged entries.  The new database that is created does not even contain any folders below the root folder.

My first thought is that I am misunderstanding how to set it up.
I will attached a PDF that shows screen-shots of how I have set it up.  I really want this to work.

Thank you for creating this plugin.  Once I get it working it will be VERY useful to me.

~BIL
[KeePassSubsetExport--Issue.pdf](https://github.com/lukeIam/KeePassSubsetExport/files/6313476/KeePassSubsetExport--Issue.pdf)

**Comment by lukeIam** [comment]
Hi @BilRadaker ,

the top three images look good. For the remaining two: it looks like you tired to "tagged" your entries via a string field - is that correct?
Just use the "normal" tags of keepass instead and it should work:
![image](https://user-images.githubusercontent.com/5115160/114893440-fcebb000-9e0d-11eb-9c28-c827bc5ac3c8.png)
My tags here are `Handy` and `SmartHome`, yours should be `Users` in your example. 

Hope this helps...

**Comment by BilRadaker** [comment]
I wasn't aware of the existence of "Normal Tags" in KeePass.  
It is working great now.  I appreciate the quick response.

Thank you, sir!
