### ISSUE TITLE
Question: is it possible to export to google drive?

### ISSUE THREAD

**Issue by Elvagor** [lukeIam/KeePassSubsetExport#49]
Hi and thanks for this great plugin!

As per the subject: would it be possible, either directly from KeePassSubsetExport or in combination with an additional plugin, to export to Google Drive?

Thanks!

**Comment by lukeIam** [comment]
Hi @Elvagor ,

KeePassSubsetExport just exports the file to a folder on your system. If you use any tool that can sync this folder with your gdrive it should work.
