### ISSUE TITLE
2.50 incompatible

### ISSUE THREAD

**Issue by lollita** [lukeIam/KeePassSubsetExport#51]
The follow plugin is incompatible with the current Keepass version 2.50

**Comment by lukeIam** [comment]
Thanks for the heads up.
I'll have a look in the next few days.

**Comment by lukeIam** [comment]
Hi @lollita,

can you give a bit more detail about the problem you are facing with KeePassSubsetExport?

For me it works fine with KeePass 2.50: no errors and the new entry was in the export database...

**Comment by lollita** [comment]
This is my ScreenShot:
[https://interno.altervista.org/temp/KeePassSubsetExport.png](url)

**Comment by lollita** [comment]
It is really strange.
If I put the file in the the plugin folder I get the incompatibility.
But if I copy the file in other other folder and put a symbolick link to plugin folder it work.
Why?

**Comment by lukeIam** [comment]
Try placing the plgx file next to the `KeePass.exe` (== next not in the `Plugins` folder).
I installed all my plugins that way...

**Comment by lollita** [comment]
I have already placed the plgx file next to the KeePass.exe (== next to the Plugins folder).
But if I place the file not work. Work only if I place a symbolic link to file.
I'm also trying but it nothing do.

**Comment by lukeIam** [comment]
Thats how I run my productive instance:
![image](https://user-images.githubusercontent.com/5115160/156930778-77563558-f7e5-45c7-bcdf-97f0f33cd4d6.png)

Does other plugins work for you? If also not maybe ask the question here: https://sourceforge.net/p/keepass/discussion/329221/

**Comment by lollita** [comment]
I tried the plugin for a long time, but I couldn't get anything.
I don't know if because it is loaded with a symbolic link.
I loaded a [simple example](https://interno.altervista.org/temp/TEST_KeePassSubsetExport.zip) with PWD 1234 if you want to try it and give me an opinion.

**Comment by lukeIam** [comment]
Your example is working for me (Windows, no symlinks, both files in the same folder, KeePass 2.50).
Just edited the username of your test entry in the Database file and it was pushed to the Database2 file.

**Comment by lollita** [comment]
To me it not work.
I can think that even if it loads the plugin with the symbolic link, however it doesn't work because it is incompatible as when it loads it directly.
I try to ask the Keepass forum.
ty.

**Comment by lollita** [comment]
I have create a thread in [Keepass forum](https://sourceforge.net/p/keepass/discussion/329221/thread/95b548e72d/).

**Comment by lollita** [comment]
I have solved overwriting the KeePass.config.xml with original.

**Comment by lukeIam** [comment]
closed as unrelated
