### ISSUE TITLE
BUG: database-options and untagged Root-Folder

### ISSUE THREAD

**Issue by electronicm** [lukeIam/KeePassSubsetExport#56]
We work with two databases: personal and global.
- Our Config: ![image](https://user-images.githubusercontent.com/13643227/178298142-64a9058f-67bd-4f88-a066-ed399f0d8b8e.png)
- In the global one, the root folder and the database name are "Global". The database color is red.
- The personal ones are called "Persönlich" and have no color.
- in the root folder is the folder "Administration" and only this folder has the tag "GlobalDB". So according to SubsetExport_Tag only this folder and subordinate folders should be exported.

However, when exporting, the following data will also be transferred:
- Database name
- Database color
- Root folder with UUID

After an import of the "Global" the 'Personal' is also displayed as "Global", color and name are also changed.

Can you please have a look at this?
If I can help in any way, let me know.

**Comment by lukeIam** [comment]
Hi @electronicm,

sorry it took me some time to actually work on it.
I introduced a new setting: `ExportDatebaseSettings` (defaults to `true`).
Please try this build:
https://lukeiam.visualstudio.com/65ae3512-9e36-4185-b514-aeac74a21017/_apis/build/builds/124/artifacts?artifactName=PGLX-Version&api-version=7.0&%24format=zip
