### ISSUE TITLE
Export to URL

### ISSUE THREAD

**Issue by Mrothyr** [lukeIam/KeePassSubsetExport#57]
Hi,

I use your plugin frequently for export to my mobile (keepass2android). 

Now the question: Can you support export to WebDAV, like "save to URL" from KeePass?

Thanks for your work :)

**Comment by lukeIam** [comment]
Hi @Mrothyr,

good idea!
I build something supporting "save to URL" targets.
Some specialty: the `SubsetExport_TargetFilePath` field must have the following schema:
`<protocol>://<username>:<password>@<host>:<port(optional)>/<pathAndFileName>`

Please try this build:
https://lukeiam.visualstudio.com/65ae3512-9e36-4185-b514-aeac74a21017/_apis/build/builds/125/artifacts?artifactName=PGLX-Version&api-version=7.0&%24format=zip

**Comment by Mrothyr** [comment]
Hi,

I make a first shot with your build with ftp and it work. I will add it with my nextcloud as WebDAV target and test it a few days.

**Comment by Mrothyr** [comment]
OK, one thing happen: the basic authentication within the URI is problematic. You cannot use all of ASCII codes, the authentication failed at my side with '#' in the password.

I think this is not a problem of your plugin. Its a problem of the logon method and depends on several factors like the http daemon. But it must be noted in the docs. So is better to use a much longer but not complex password (https://xkcd.com/936/ :D)

**Comment by lukeIam** [comment]
> OK, one thing happen: the basic authentication within the URI is problematic. You cannot use all of ASCII codes, the authentication failed at my side with '#' in the password.

good catch - yes special chars from a url don't work: e.g. `#`, `@`, `?`, `:`, ` `, `/` .
This restriction is basically coming from the C# Uri class.

**Comment by lukeIam** [comment]
i played around with supporting escaping but itself keepass seems to have a problem with it too.
so it might be better just to document the restriction.

**Comment by Mrothyr** [comment]
So, this happens with my Nextcloud:

"SubsetExport failed: Die zugrundeliegende Verbindung wurde geschlossen: Unerwarteter Fehler beim Senden."

English: The underlying connection was closed: An unexpected error occured while sending.

The Nextcloud have a certificate from lets encrypt, login with the same credentials is ok. No errors in the server log, no extra chars in password.

CU

**Comment by Mrothyr** [comment]
> hmm do you also get this error when you save manually in KeePass? (we are using the save mechanism of KeePass)

You are right, it doesn't work. I look deeper - it's look like the FastCGI interface at the webserver daemon filter the header. Not your problem, sorry.

**Comment by lukeIam** [comment]
Hi @Mrothyr,

no problem ;)

**Comment by Mrothyr** [comment]
Hi,

I switched to nginx, the authentication header are now transfered to php-fpm. It works as espected, also with application passwords. A little problem is the user agent - KeePass use a unusual approach for it. From https://keepass.info/help/v2/triggers.html:

Most trigger actions having a file path/URL parameter only allow specifying the path/URL and possibly credentials (user name and password) for accessing the file; advanced connection properties (like timeout, user agent, passive mode, etc.) cannot be specified here. If advanced connection properties are required, open the file once (using 'File' → 'Open') with the desired connection properties. This will create an item in the 'Open Recent' file list (which remembers connection properties). When a trigger action is executed, KeePass loads the connection properties from the corresponding item (same path/URL) in the 'Open Recent' file list.

I use the open dialogue to put the database in the recent file list - but the user agent is already blank. Not a problem here - I can use clients with blank user agent. But in other cases the application password is bound at the user agent - so blank user agent is a source of errors. I think, the user agent should be predefined from KeePass - it's normally not a user changeable parameter.
