### ISSUE TITLE
RFE: export by folder

### ISSUE THREAD

**Issue by sgiunchi** [lukeIam/KeePassSubsetExport#6]
Hi, great plugin, I tried it and it worked flawlessly with structure and icons.
I ask you if you can add a per-folder export and not only per-tag.
I have a file with a folder for every client, and I would like to update client's export files on every save.

thanks

**Comment by lukeIam** [comment]
Hi @sgiunchi thank for having a look at my plugin.
Currently I do not have much time for my programming projects, but I'll have a look and check if the the folder option is possible without breaking other things.

**Comment by lukeIam** [comment]
@sgiunchi please test PR #9
